# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.resize(671, 618)
        MainForm.setMaximumSize(QtCore.QSize(1920, 1080))
        MainForm.setSizeIncrement(QtCore.QSize(671, 618))
        self.listWidgetContact = QtWidgets.QListWidget(MainForm)
        self.listWidgetContact.setGeometry(QtCore.QRect(10, 30, 256, 511))
        self.listWidgetContact.setObjectName("listWidgetContact")
        self.listWidgetMessage = QtWidgets.QListWidget(MainForm)
        self.listWidgetMessage.setGeometry(QtCore.QRect(280, 30, 381, 511))
        self.listWidgetMessage.setObjectName("listWidgetMessage")
        self.label = QtWidgets.QLabel(MainForm)
        self.label.setGeometry(QtCore.QRect(10, 10, 51, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(MainForm)
        self.label_2.setGeometry(QtCore.QRect(280, 10, 58, 13))
        self.label_2.setObjectName("label_2")
        self.pushButtonAddContact = QtWidgets.QPushButton(MainForm)
        self.pushButtonAddContact.setGeometry(QtCore.QRect(10, 580, 103, 23))
        self.pushButtonAddContact.setObjectName("pushButtonAddContact")
        self.pushButtonDeleteContact = QtWidgets.QPushButton(MainForm)
        self.pushButtonDeleteContact.setGeometry(QtCore.QRect(170, 580, 97, 23))
        self.pushButtonDeleteContact.setObjectName("pushButtonDeleteContact")
        self.lineEditMesssag = QtWidgets.QLineEdit(MainForm)
        self.lineEditMesssag.setGeometry(QtCore.QRect(280, 550, 381, 31))
        self.lineEditMesssag.setObjectName("lineEditMesssag")
        self.pushButtonPostMassege = QtWidgets.QPushButton(MainForm)
        self.pushButtonPostMassege.setGeometry(QtCore.QRect(590, 590, 75, 23))
        self.pushButtonPostMassege.setObjectName("pushButtonPostMassege")
        self.lineEditContact = QtWidgets.QLineEdit(MainForm)
        self.lineEditContact.setGeometry(QtCore.QRect(80, 550, 113, 20))
        self.lineEditContact.setObjectName("lineEditContact")
        self.pushButtonContactUpdate = QtWidgets.QPushButton(MainForm)
        self.pushButtonContactUpdate.setGeometry(QtCore.QRect(190, 0, 75, 23))
        self.pushButtonContactUpdate.setObjectName("pushButtonContactUpdate")

        self.retranslateUi(MainForm)
        QtCore.QMetaObject.connectSlotsByName(MainForm)

    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "Form"))
        self.label.setText(_translate("MainForm", "Контакты"))
        self.label_2.setText(_translate("MainForm", "Сообщения"))
        self.pushButtonAddContact.setText(_translate("MainForm", "Добавить контакт"))
        self.pushButtonDeleteContact.setText(_translate("MainForm", "Удалить контакт"))
        self.pushButtonPostMassege.setText(_translate("MainForm", "Отправить"))
        self.pushButtonContactUpdate.setText(_translate("MainForm", "Обновить"))
