ACCOUNT_NAME: account_name
ACTION: action
DEFAULT_IP_ADDRESS: 127.0.0.1
DEFAULT_PORT: 8888
ENCODING: utf-8
ERROR: error
MAX_CONNECTIONS: 5
MAX_PACKAGE_LENGTH: 1000000
PRESENCE: presence
RESPONSE: response
TIME: time
USER: user
